# This file was generated by GoReleaser. DO NOT EDIT.
cask "pyck" do
  version "0.7.5"

  on_macos do
    on_intel do
      sha256 "0eb95e46d8ace0c093e718e2b0de103400eae7d43efaf154a1e8214f8e2e72b5"
      url "https://github.com/pyck-ai/pyck-cli/releases/download/v#{version}/pyck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c6aea458fa0f0de2036b29cb30aa58cbf876c69c729df3256685906c70e91cfb"
      url "https://github.com/pyck-ai/pyck-cli/releases/download/v#{version}/pyck_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "29a9e1b9a11e5b37f5ba78167010fb4c9e49189827b7841563113e900f348da7"
      url "https://github.com/pyck-ai/pyck-cli/releases/download/v#{version}/pyck_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d96072d27d490b8a2ac3f9643c555f6e5bb7de8792e39f6249779a70b7e8f0d"
      url "https://github.com/pyck-ai/pyck-cli/releases/download/v#{version}/pyck_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pyck"
  desc "CLI for the pyck platform"
  homepage "https://github.com/pyck-ai/pyck-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pyck"

  # No zap stanza required

end
