# This file was generated by GoReleaser. DO NOT EDIT.
cask "pyck" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "56e869d3a531c4d0497b82ff1af4e2fd6e750a882ae5960770759807b702f7d2"
      url "https://github.com/pyck-ai/pyck-cli/releases/download/v#{version}/pyck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "00f541f22547ad3f514dba5c4a2c048c10a395820fdb5380440d5cde451d43b6"
      url "https://github.com/pyck-ai/pyck-cli/releases/download/v#{version}/pyck_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ac0fb68bf576480a372842045c86cddd8758f1efffe4bfdcfa751df7cd23cb75"
      url "https://github.com/pyck-ai/pyck-cli/releases/download/v#{version}/pyck_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d4d1ca1f4555283d2793344c26a66b22005f0e3ebc533bdae6df85b5366913c9"
      url "https://github.com/pyck-ai/pyck-cli/releases/download/v#{version}/pyck_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pyck"
  desc "CLI for the pyck platform"
  homepage "https://github.com/pyck-ai/pyck-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pyck"

  # No zap stanza required

end
