# This file was generated by GoReleaser. DO NOT EDIT.
cask "pyck" do
  version "0.2.4"

  on_macos do
    on_intel do
      url "https://github.com/pyck-ai/cli/releases/download/v#{version}/pyck_#{version}_darwin_amd64.tar.gz"
      sha256 "de563875646389386b020a8592c276b267877f5d78e828f3f80114d9a09d0326"
    end
    on_arm do
      url "https://github.com/pyck-ai/cli/releases/download/v#{version}/pyck_#{version}_darwin_arm64.tar.gz"
      sha256 "3114d4c964cfcc05fbff3e8f56b93a042b54828b092027632368bad7d51b6c53"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pyck-ai/cli/releases/download/v#{version}/pyck_#{version}_linux_amd64.tar.gz"
      sha256 "c24fed0c58ee59319c385c4f01d865006e96f8dbef3f0f866930e95ec657f496"
    end
    on_arm do
      url "https://github.com/pyck-ai/cli/releases/download/v#{version}/pyck_#{version}_linux_arm64.tar.gz"
      sha256 "6bb88f4fc2a9d3e5b35b91b78a2e8f4a1d1caca1046c95e5d50c15b445d7b2c0"
    end
  end

  name "pyck"
  desc "CLI for the pyck platform"
  homepage "https://github.com/pyck-ai/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pyck"

  # No zap stanza required

end
